// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: tapmonrpc.proto

package tapmonrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rarity int32

const (
	Rarity_COMMON    Rarity = 0
	Rarity_RARE      Rarity = 1
	Rarity_EPIC      Rarity = 2
	Rarity_LEGENDARY Rarity = 3
)

// Enum value maps for Rarity.
var (
	Rarity_name = map[int32]string{
		0: "COMMON",
		1: "RARE",
		2: "EPIC",
		3: "LEGENDARY",
	}
	Rarity_value = map[string]int32{
		"COMMON":    0,
		"RARE":      1,
		"EPIC":      2,
		"LEGENDARY": 3,
	}
)

func (x Rarity) Enum() *Rarity {
	p := new(Rarity)
	*p = x
	return p
}

func (x Rarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rarity) Descriptor() protoreflect.EnumDescriptor {
	return file_tapmonrpc_proto_enumTypes[0].Descriptor()
}

func (Rarity) Type() protoreflect.EnumType {
	return &file_tapmonrpc_proto_enumTypes[0]
}

func (x Rarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rarity.Descriptor instead.
func (Rarity) EnumDescriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{0}
}

type GetMonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMonRequest) Reset() {
	*x = GetMonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonRequest) ProtoMessage() {}

func (x *GetMonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonRequest.ProtoReflect.Descriptor instead.
func (*GetMonRequest) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetMonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMonRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetMonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mon *Mon `protobuf:"bytes,1,opt,name=mon,proto3" json:"mon,omitempty"`
}

func (x *GetMonResponse) Reset() {
	*x = GetMonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonResponse) ProtoMessage() {}

func (x *GetMonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonResponse.ProtoReflect.Descriptor instead.
func (*GetMonResponse) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetMonResponse) GetMon() *Mon {
	if x != nil {
		return x.Mon
	}
	return nil
}

type ListOwnedMonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOwnedMonsRequest) Reset() {
	*x = ListOwnedMonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOwnedMonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedMonsRequest) ProtoMessage() {}

func (x *ListOwnedMonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedMonsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnedMonsRequest) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{2}
}

type ListOwnedMonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mons []*Mon `protobuf:"bytes,1,rep,name=mons,proto3" json:"mons,omitempty"`
}

func (x *ListOwnedMonsResponse) Reset() {
	*x = ListOwnedMonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOwnedMonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedMonsResponse) ProtoMessage() {}

func (x *ListOwnedMonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedMonsResponse.ProtoReflect.Descriptor instead.
func (*ListOwnedMonsResponse) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{3}
}

func (x *ListOwnedMonsResponse) GetMons() []*Mon {
	if x != nil {
		return x.Mons
	}
	return nil
}

type ListAllMonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListAllMonsRequest) Reset() {
	*x = ListAllMonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllMonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMonsRequest) ProtoMessage() {}

func (x *ListAllMonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMonsRequest.ProtoReflect.Descriptor instead.
func (*ListAllMonsRequest) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllMonsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAllMonsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAllMonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mons []*Mon `protobuf:"bytes,1,rep,name=mons,proto3" json:"mons,omitempty"`
}

func (x *ListAllMonsResponse) Reset() {
	*x = ListAllMonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAllMonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllMonsResponse) ProtoMessage() {}

func (x *ListAllMonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllMonsResponse.ProtoReflect.Descriptor instead.
func (*ListAllMonsResponse) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListAllMonsResponse) GetMons() []*Mon {
	if x != nil {
		return x.Mons
	}
	return nil
}

type MintMonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MintMonRequest) Reset() {
	*x = MintMonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintMonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMonRequest) ProtoMessage() {}

func (x *MintMonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMonRequest.ProtoReflect.Descriptor instead.
func (*MintMonRequest) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{6}
}

func (x *MintMonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MintMonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mon *Mon `protobuf:"bytes,1,opt,name=mon,proto3" json:"mon,omitempty"`
}

func (x *MintMonResponse) Reset() {
	*x = MintMonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MintMonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintMonResponse) ProtoMessage() {}

func (x *MintMonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintMonResponse.ProtoReflect.Descriptor instead.
func (*MintMonResponse) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{7}
}

func (x *MintMonResponse) GetMon() *Mon {
	if x != nil {
		return x.Mon
	}
	return nil
}

type LevelMonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestedLevel int32  `protobuf:"varint,2,opt,name=requested_level,json=requestedLevel,proto3" json:"requested_level,omitempty"`
	StartAtNonce   int64  `protobuf:"varint,3,opt,name=start_at_nonce,json=startAtNonce,proto3" json:"start_at_nonce,omitempty"`
}

func (x *LevelMonRequest) Reset() {
	*x = LevelMonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelMonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelMonRequest) ProtoMessage() {}

func (x *LevelMonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelMonRequest.ProtoReflect.Descriptor instead.
func (*LevelMonRequest) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{8}
}

func (x *LevelMonRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LevelMonRequest) GetRequestedLevel() int32 {
	if x != nil {
		return x.RequestedLevel
	}
	return 0
}

func (x *LevelMonRequest) GetStartAtNonce() int64 {
	if x != nil {
		return x.StartAtNonce
	}
	return 0
}

type LevelMonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce int64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *LevelMonResponse) Reset() {
	*x = LevelMonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelMonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelMonResponse) ProtoMessage() {}

func (x *LevelMonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelMonResponse.ProtoReflect.Descriptor instead.
func (*LevelMonResponse) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{9}
}

func (x *LevelMonResponse) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Mon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          []byte    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes  []int32   `protobuf:"varint,3,rep,packed,name=attributes,proto3" json:"attributes,omitempty"`
	RarityScore float64   `protobuf:"fixed64,4,opt,name=rarity_score,json=rarityScore,proto3" json:"rarity_score,omitempty"`
	Level       *MonLevel `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Mon) Reset() {
	*x = Mon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mon) ProtoMessage() {}

func (x *Mon) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mon.ProtoReflect.Descriptor instead.
func (*Mon) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{10}
}

func (x *Mon) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Mon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mon) GetAttributes() []int32 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Mon) GetRarityScore() float64 {
	if x != nil {
		return x.RarityScore
	}
	return 0
}

func (x *Mon) GetLevel() *MonLevel {
	if x != nil {
		return x.Level
	}
	return nil
}

type MonLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level int32  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *MonLevel) Reset() {
	*x = MonLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tapmonrpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonLevel) ProtoMessage() {}

func (x *MonLevel) ProtoReflect() protoreflect.Message {
	mi := &file_tapmonrpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonLevel.ProtoReflect.Descriptor instead.
func (*MonLevel) Descriptor() ([]byte, []int) {
	return file_tapmonrpc_proto_rawDescGZIP(), []int{11}
}

func (x *MonLevel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MonLevel) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

var File_tapmonrpc_proto protoreflect.FileDescriptor

var file_tapmonrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x22, 0x33, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x32, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e,
	0x52, 0x03, 0x6d, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e,
	0x65, 0x64, 0x4d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4d, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63,
	0x2e, 0x4d, 0x6f, 0x6e, 0x52, 0x04, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x39,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x6f, 0x6e, 0x52, 0x04, 0x6d, 0x6f, 0x6e, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x4d, 0x69, 0x6e,
	0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x33, 0x0a, 0x0f, 0x4d, 0x69, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x52,
	0x03, 0x6d, 0x6f, 0x6e, 0x22, 0x70, 0x0a, 0x0f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x24, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41,
	0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x22, 0x97, 0x01, 0x0a, 0x03, 0x4d, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x29, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x36, 0x0a, 0x08, 0x4d, 0x6f,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x2a, 0x37, 0x0a, 0x06, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x41, 0x52, 0x45,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x50, 0x49, 0x43, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x4c, 0x45, 0x47, 0x45, 0x4e, 0x44, 0x41, 0x52, 0x59, 0x10, 0x03, 0x32, 0xf0, 0x02, 0x0a, 0x06,
	0x54, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e,
	0x12, 0x18, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x61, 0x70,
	0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e,
	0x65, 0x64, 0x4d, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72,
	0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4d, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x4d, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f,
	0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x4d, 0x69, 0x6e, 0x74, 0x4d,
	0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x69, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x69, 0x6e, 0x74, 0x4d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x4d, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70,
	0x63, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x4d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x75,
	0x74, 0x6e, 0x31, 0x63, 0x6b, 0x2f, 0x74, 0x61, 0x70, 0x6d, 0x6f, 0x6e, 0x64, 0x2f, 0x74, 0x61,
	0x70, 0x6d, 0x6f, 0x6e, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tapmonrpc_proto_rawDescOnce sync.Once
	file_tapmonrpc_proto_rawDescData = file_tapmonrpc_proto_rawDesc
)

func file_tapmonrpc_proto_rawDescGZIP() []byte {
	file_tapmonrpc_proto_rawDescOnce.Do(func() {
		file_tapmonrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tapmonrpc_proto_rawDescData)
	})
	return file_tapmonrpc_proto_rawDescData
}

var file_tapmonrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tapmonrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tapmonrpc_proto_goTypes = []any{
	(Rarity)(0),                   // 0: tapmonrpc.Rarity
	(*GetMonRequest)(nil),         // 1: tapmonrpc.GetMonRequest
	(*GetMonResponse)(nil),        // 2: tapmonrpc.GetMonResponse
	(*ListOwnedMonsRequest)(nil),  // 3: tapmonrpc.ListOwnedMonsRequest
	(*ListOwnedMonsResponse)(nil), // 4: tapmonrpc.ListOwnedMonsResponse
	(*ListAllMonsRequest)(nil),    // 5: tapmonrpc.ListAllMonsRequest
	(*ListAllMonsResponse)(nil),   // 6: tapmonrpc.ListAllMonsResponse
	(*MintMonRequest)(nil),        // 7: tapmonrpc.MintMonRequest
	(*MintMonResponse)(nil),       // 8: tapmonrpc.MintMonResponse
	(*LevelMonRequest)(nil),       // 9: tapmonrpc.LevelMonRequest
	(*LevelMonResponse)(nil),      // 10: tapmonrpc.LevelMonResponse
	(*Mon)(nil),                   // 11: tapmonrpc.Mon
	(*MonLevel)(nil),              // 12: tapmonrpc.MonLevel
}
var file_tapmonrpc_proto_depIdxs = []int32{
	11, // 0: tapmonrpc.GetMonResponse.mon:type_name -> tapmonrpc.Mon
	11, // 1: tapmonrpc.ListOwnedMonsResponse.mons:type_name -> tapmonrpc.Mon
	11, // 2: tapmonrpc.ListAllMonsResponse.mons:type_name -> tapmonrpc.Mon
	11, // 3: tapmonrpc.MintMonResponse.mon:type_name -> tapmonrpc.Mon
	12, // 4: tapmonrpc.Mon.level:type_name -> tapmonrpc.MonLevel
	1,  // 5: tapmonrpc.Tapmon.GetMon:input_type -> tapmonrpc.GetMonRequest
	3,  // 6: tapmonrpc.Tapmon.ListOwnedMons:input_type -> tapmonrpc.ListOwnedMonsRequest
	5,  // 7: tapmonrpc.Tapmon.ListAllMons:input_type -> tapmonrpc.ListAllMonsRequest
	7,  // 8: tapmonrpc.Tapmon.MintMon:input_type -> tapmonrpc.MintMonRequest
	9,  // 9: tapmonrpc.Tapmon.LevelMon:input_type -> tapmonrpc.LevelMonRequest
	2,  // 10: tapmonrpc.Tapmon.GetMon:output_type -> tapmonrpc.GetMonResponse
	4,  // 11: tapmonrpc.Tapmon.ListOwnedMons:output_type -> tapmonrpc.ListOwnedMonsResponse
	6,  // 12: tapmonrpc.Tapmon.ListAllMons:output_type -> tapmonrpc.ListAllMonsResponse
	8,  // 13: tapmonrpc.Tapmon.MintMon:output_type -> tapmonrpc.MintMonResponse
	10, // 14: tapmonrpc.Tapmon.LevelMon:output_type -> tapmonrpc.LevelMonResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tapmonrpc_proto_init() }
func file_tapmonrpc_proto_init() {
	if File_tapmonrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tapmonrpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetMonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetMonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListOwnedMonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListOwnedMonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ListAllMonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListAllMonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MintMonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MintMonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LevelMonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*LevelMonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Mon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tapmonrpc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*MonLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tapmonrpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tapmonrpc_proto_goTypes,
		DependencyIndexes: file_tapmonrpc_proto_depIdxs,
		EnumInfos:         file_tapmonrpc_proto_enumTypes,
		MessageInfos:      file_tapmonrpc_proto_msgTypes,
	}.Build()
	File_tapmonrpc_proto = out.File
	file_tapmonrpc_proto_rawDesc = nil
	file_tapmonrpc_proto_goTypes = nil
	file_tapmonrpc_proto_depIdxs = nil
}
