// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: mons.sql

package sqlc

import (
	"context"
)

const getKnownMons = `-- name: GetKnownMons :many
SELECT id, block FROM known_mons
`

func (q *Queries) GetKnownMons(ctx context.Context) ([]KnownMon, error) {
	rows, err := q.db.QueryContext(ctx, getKnownMons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnownMon
	for rows.Next() {
		var i KnownMon
		if err := rows.Scan(&i.ID, &i.Block); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
