// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetKnownMons(ctx context.Context) ([]KnownMon, error)
}

var _ Querier = (*Queries)(nil)
